#ifndef TILAKONERFIDDLL_GLOBAL_H
#define TILAKONERFIDDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TILAKONERFIDDLL_LIBRARY)
#  define TILAKONERFIDDLL_EXPORT Q_DECL_EXPORT
#else
#  define TILAKONERFIDDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // TILAKONERFIDDLL_GLOBAL_H
